In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb


dataframe = pd.read_csv('../querys/crecimientoNicolasRomero.csv')
dataframe.head(10)

,numero conteo,ID,Clee,Nombre_de_la_Unidad_Económica,Razón social,Código_de_la_clase_de_actividad_SCIAN,Nombre_de_clase_de_la_actividad,Descripcion estrato personal ocupado,Tipo de vialidad,Nombre de la vialidad,...,Localidad,Área_geoestadística_básica,Manzana,Número de teléfono,Correo electrónico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha_de_incorporacion_al_DENUE
0,1,9045956,15060114119000032000000000U1,CRIANZA ENGORDA Y COMERCIALIZADORA DE TRUCHAS ...,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",6 a 10 personas,OTRO (ESPECIFIQUE),las manzanitas,...,Las Espinas,471,800,5.513182e+09,NaN,NaN,Fijo,19.616022,-99.440017,2019-11
1,2,6170967,15060112512000031000000000U1,DESARROLLO ECOTURISTICO 3 PIEDRAS,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,CALLEJON,PARAJE RIO HONDO,...,Miranda,471,800,5.522769e+09,NaN,NaN,Fijo,19.639881,-99.432803,2010-07
2,3,9017141,15060112512000091000000000U5,EL POLVORIN 2,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,OTRO (ESPECIFIQUE),NINGUNO,...,Las Espinas,471,800,5.511705e+09,NaN,NaN,Fijo,19.588705,-99.422713,2019-11
3,4,8806146,15060112512000062000000000U6,GRANJA DE TRUCHAS EL POLVORIN,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,OTRO (ESPECIFIQUE),LAS TRUCHAS,...,Loma de Chapultepec,471,800,5.564033e+09,NaN,NaN,Fijo,19.604402,-99.417793,2019-11
4,5,9045955,15060114119000022000000000U2,GRANJA DE TRUCHAS RANCHO EL PARAISO,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",6 a 10 personas,OTRO (ESPECIFIQUE),ninguno,...,Miranda,471,800,5.534853e+09,ADI.TEM@HOTMAIL.COM,NaN,Fijo,19.638993,-99.427058,2019-11
5,6,8835831,15060112512000041000000000U0,GRANJA EL TULAR,GRANJA EL TULAR,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,OTRO (ESPECIFIQUE),NINGUNO,...,Las Espinas,471,800,5.515787e+09,NaN,NaN,Fijo,19.596797,-99.442496,2019-11
6,7,9046020,15060114119000041000000000U2,LA CANTERA II,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,OTRO (ESPECIFIQUE),planta villada,...,Las Espinas,471,800,NaN,NaN,NaN,Fijo,19.616022,-99.440017,2019-11
7,8,8203577,15060112512000081000000000U6,LOS TRES POTRILLOS,LOS TRES POTRILLOS,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,OTRO (ESPECIFIQUE),NICOLAS ROMERO-JILOTZINGO,...,El Tanque,486,800,5.532111e+09,NaN,NaN,Fijo,19.591583,-99.358893,2019-11
8,9,8443622,15060112512000073000000000U3,TRUCHAS CHIRANI,TRUCHAS CHIRANI,112512,"Piscicultura y otra acuicultura, excepto camar...",6 a 10 personas,OTRO (ESPECIFIQUE),NICOLAS ROMERO-JILOTZINGO,...,El Tanque,486,800,NaN,NaN,NaN,Fijo,19.591583,-99.358893,2019-11
9,10,7863384,15060114119000012000000000U3,TRUCHAS CIELITO LINDO,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,CALLE,Francisco villa,...,Barrio de Guadalupe,486,1,5.566349e+09,NaN,NaN,Fijo,19.601580,-99.420113,2019-11

In [6]:
dataframe.describe()

,numero conteo,ID,Código_de_la_clase_de_actividad_SCIAN,Número exterior o kilómetro,Número interior,Código Postal,Clave entidad,Clave municipio,Clave localidad,Manzana,Número de teléfono,Latitud,Longitud
count,16243.000000,1.624300e+04,16243.000000,7260.000000,4756.000000,16134.000000,16243.0,16243.0,16243.000000,16243.000000,3.619000e+03,16243.000000,16243.000000
mean,8122.000000,5.162829e+06,547241.154897,30.342287,1.732759,54440.134932,15.0,60.0,5.082682,24.173921,9.785599e+09,19.619577,-99.313725
std,4689.094547,2.863400e+06,153447.349899,254.549506,15.328285,384.853716,0.0,0.0,14.631196,32.370947,9.882082e+10,0.018664,0.031627
min,1.000000,2.236925e+06,112512.000000,0.000000,0.000000,6020.000000,15.0,60.0,1.000000,1.000000,0.000000e+00,19.573532,-99.500000
25%,4061.500000,2.414189e+06,461110.000000,0.000000,0.000000,54416.000000,15.0,60.0,1.000000,9.000000,5.523358e+09,19.605780,-99.322630
50%,8122.000000,2.472477e+06,465311.000000,3.000000,0.000000,54440.000000,15.0,60.0,1.000000,19.000000,5.542941e+09,19.619014,-99.307118
75%,12182.500000,7.914368e+06,722511.000000,30.000000,0.000000,54469.000000,15.0,60.0,1.000000,32.000000,5.561408e+09,19.629627,-99.292316
max,16243.000000,9.387368e+06,931810.000000,20080.000000,404.000000,55000.000000,15.0,60.0,100.000000,800.000000,5.516824e+12,19.692578,-99.267305